name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: nibbler
      volumes:
      - ${{ github.workspace }}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: node main.js
        working-directory: /app/
        env:
          DATA_PATH: "${{ github.workspace }}"
      - run: ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
